{{ $root := . }}
{{ range $path, $bytes := .Files.Glob "helm-data/data.zip.**"  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ base $path }}
binaryData:
  {{ base $path }}: |-
    {{ $root.Files.Get $path | b64enc }}
---

{{ end }}

{{ $root := . }}
{{ range $path, $bytes := .Files.Glob "helm-data/data.zip.**"  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ base $path }}-win
binaryData:
  {{ base $path }}: |-
    {{ $root.Files.Get $path | b64enc }}
---

{{ end }}



