apiVersion: v1
kind: ConfigMap
metadata:
  name: init-container-startup
data: 
  startup.sh: |-
    {{ .Files.Get "scripts/init-container-startup.sh" | nindent 4 }}
  startup.ps1: |-
    {{ .Files.Get "scripts/init-container-startup.ps1" | nindent 4 }}
