{{ $root := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-container-linux-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-container-linux-debug
  template:
    metadata:
      labels:
        app: init-container-linux-debug
    spec:
      containers:
      - name: init-container-debug
        command: [ "sleep" ]
        args: ["1024d" ]
        {{ include "init-container" . | nindent 8 }}
      volumes:
        {{ include "init-volumes" . | nindent 8 }}
      nodeSelector:
        beta.kubernetes.io/os: linux

---

{{ $root := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-container-win-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-container-win-debug
  template:
    metadata:
      labels:
        app: init-container-win-debug
    spec:
      containers:
      - name: main
        command: ["ping"]
        args: ["-t",  "127.0.0.1" ]
        {{ include "init-container-win" . | nindent 8 }}
      volumes:
        {{ include "init-volumes" . | nindent 8 }}
      nodeSelector:
        beta.kubernetes.io/os: windows


