{{ $root := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: "ubuntu:18.04"
        command: [ "sleep" ]
        args: ["infinity" ]
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
      initContainers:
      - name: unzip
        image: "alpine"
        command: [ "bash" ]
        args: ["/etc/startup/startup.sh" ]
        {{ include "init-container" . | nindent 8 }}
      volumes:
        {{ include "init-volumes" . | nindent 8 }}
