{{ $root := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: "ubuntu:18.04"
        command: [ "sleep" ]
        args: ["infinity" ]
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
      initContainers:
      - name: unzip
        image: "alpine"
        command: [ "bash" ]
        args: ["/etc/startup/startup.sh" ]
      volumes:
        {{ include "init-volumes" . | nindent 8 }}


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows
  labels:
    app: windows
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windows
  template:
    metadata:
      labels:
        app: windows
    spec:
      containers:
      - name: windows
        image: "registry.k8s.local/windows-7z"
        command: ["ping"]
        args: ["-t",  "127.0.0.1" ]
        volumeMounts:
          - name: config
            mountPath: c:/config
          - name: startup
            mountPath: c:/etc/startup
      initContainers:
      - name: init
        command: [ "powershell" ]
        args: ["/etc/startup/startup.ps1" ]
        {{ include "init-container-win" . | nindent 8 }}
      volumes:
        {{ include "init-volumes" . | nindent 8 }}
