{{ $root := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-container-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: init-container-debug
        command: [ "sleep" ]
        args: ["1024d" ]
        {{ include "init-container" . | nindent 8 }}
      volumes:
        {{ include "init-volumes" . | nindent 8 }}
